# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4e7a9a6ec84d5cd3c0869eb65f0dcc5db3f5b3c73be7803316f4ee091e5a7dcb2668d3d1e0c4354df3a076b83462569c2068ee9b3eb30958ca7d5e4dc6f7e30

test:
  secret_key_base: e38e0befdbed1976bc230ed224c4b39ef27f235a090057d36fade51a9958dd100a5f2bbc6e60b5ab93a81757eae1bda6f09d6e9dee0ade60c6adbc10100843c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  # to be used when testing production on local machine
  # secret_key_base: e38e0befdbed1976bc230ed224c4b39ef27f235a090057d36fade51a9958dd100a5f2bbc6e60b5ab93a81757eae1bda6f09d6e9dee0ade60c6adbc10100843c2

